version: "3.8"

services:
  spring-boot-app:
    image: your-spring-boot-image
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_social_network?createIfItNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    restart: unless-stopped

  mysql:
    image: mysql:8.0 # Using the official MySQL 8.0 image
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Set the root password for MySQL
      MYSQL_DATABASE: book_social_network # Create the database
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for MySQL data
    networks:
      - spring-demo

  mail-dev:
    container_name: mail-dev-bs
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
