spring:
  datasource:
    # Defines the database connection URL.
    url: jdbc:mysql://localhost:3306/book_social_network
    # Specifies the username for connecting to the MySQL database.
    username: root
    # The password to connect to the database (left empty here; should be populated with your password).
    password: 
    # Specifies the JDBC driver to use for MySQL.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # JPA (Java Persistence API) is used for handling ORM (Object-Relational Mapping).
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    # Mail server configuration
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 300
          writetimeout: 500

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account?token=%s

server:
  port: 8088

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE